# Generated by Django 6.0.2 on 2026-03-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
